// Default pastel avatars circulated for profiles/credits without a photo
// (e.g. HS first-author credits after the HS Foundation rebrand). Files live at
// public/assets/default-avatars/avatar-01.svg … avatar-{COUNT}.svg, generated by
// scripts/generate-default-avatars.js. Keep COUNT in sync with that script.
const COUNT = 20;

/**
 * Deterministically map a seed (e.g. an author name) to one of the default
 * avatars, so the same person always gets the same picture but the set is
 * spread across many profiles.
 */
export function defaultAvatar(seed) {
  const s = (seed || "").toString();
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) >>> 0;
  }
  const n = (h % COUNT) + 1;
  return `/assets/default-avatars/avatar-${String(n).padStart(2, "0")}.svg`;
}
